/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AspectRatio: typeof import('radix-vue')['AspectRatio']
    PaginationEllipsis: typeof import('radix-vue')['PaginationEllipsis']
    PaginationFirst: typeof import('radix-vue')['PaginationFirst']
    PaginationLast: typeof import('radix-vue')['PaginationLast']
    PaginationList: typeof import('radix-vue')['PaginationList']
    PaginationListItem: typeof import('radix-vue')['PaginationListItem']
    PaginationNext: typeof import('radix-vue')['PaginationNext']
    PaginationPrev: typeof import('radix-vue')['PaginationPrev']
    PaginationRoot: typeof import('radix-vue')['PaginationRoot']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
